# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Package Replicated applications and manage releases, channels, customers and entitlements using a command-line interface."
  homepage "https://docs.replicated.com/reference/replicated-cli-installing"
  version "0.65.0"

  on_macos do
    url "https://github.com/replicatedhq/replicated/releases/download/v0.65.0/replicated_0.65.0_darwin_all.tar.gz"
    sha256 "51810f2f9988824910ff5a72f09ba8dbbc38aec3582fc83107ecc68e5ff0ec31"

    def install
      bin.install "replicated"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/replicatedhq/replicated/releases/download/v0.65.0/replicated_0.65.0_linux_amd64.tar.gz"
      sha256 "69681d94593a342541514998c3d69003c105d7c5be40dc1653b65e47a12b0b8e"

      def install
        bin.install "replicated"
      end
    end
  end
end
