# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preflight < Formula
  desc "A preflight checker and conformance test for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/preflight-overview/"
  version "0.129.1"

  on_macos do
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.129.1/preflight_darwin_all.tar.gz"
    sha256 "8f6bee0a25f6310181d620018f84114228877763cf5c4e4c5d1326c80b3ca74e"

    def install
      bin.install "preflight"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.129.1/preflight_linux_amd64.tar.gz"
      sha256 "b1ddb9e0227668e469e4c924ee7f9128efd24ba1e0aabe9d3f73e0fc44eeed8a"
      def install
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.129.1/preflight_linux_arm.tar.gz"
      sha256 "5c70e8098b71b27f1a213a380b2699fc31b177bf112f417afa514d1f3aba32ff"
      def install
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.129.1/preflight_linux_arm64.tar.gz"
      sha256 "d23a85c0ef0727966f5e990887467780710653fbcfd80057b868488785408da1"
      def install
        bin.install "preflight"
      end
    end
  end
end
