# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preflight < Formula
  desc "A preflight checker and conformance test for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/preflight-overview/"
  version "0.123.10"

  on_macos do
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.10/preflight_darwin_all.tar.gz"
    sha256 "355b74c6444bd9ba1a3890ed54c445993794594580a3b93b313739fbddc9f4cc"

    def install
      bin.install "preflight"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.10/preflight_linux_amd64.tar.gz"
      sha256 "0a99b1eacc8f4620daabc0353b0494e124d1e31852ea8559263e9645ff29b20b"
      def install
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.10/preflight_linux_arm.tar.gz"
      sha256 "22c8ea6b9e262b8a0c67fb8bee63bbab412cf1a3fa73ddf177e9e51caf22dcb6"
      def install
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.10/preflight_linux_arm64.tar.gz"
      sha256 "514deaf4fffe08a5ce100054864b3b179b6b0d8eb95ec8eff120a6f5fce6c7ed"
      def install
        bin.install "preflight"
      end
    end
  end
end
