# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Replicated < Formula
  desc "Package Replicated applications and manage releases, channels, customers and entitlements using a command-line interface."
  homepage "https://docs.replicated.com/reference/replicated-cli-installing"
  version "0.39.2"

  on_macos do
    url "https://github.com/replicatedhq/replicated/releases/download/v0.39.2/replicated_0.39.2_darwin_all.tar.gz"
    sha256 "8490d5b6e41bb9ed7e53520c3707ecc3addc223bf17ac42252ba593835d69e82"

    def install
      bin.install "replicated"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/replicatedhq/replicated/releases/download/v0.39.2/replicated_0.39.2_linux_amd64.tar.gz"
      sha256 "26a85e76deaa64bd7f91663dcf47e540ae8744aef09fe1fdf28b45bd63229074"

      def install
        bin.install "replicated"
      end
    end
  end
end
