# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbctl < Formula
  desc "Explore a Kubernetes support bundle with kubectl."
  homepage "https://github.com/replicatedhq/sbctl"
  version "0.17.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/replicatedhq/sbctl/releases/download/v0.17.5/sbctl_darwin_amd64.tar.gz"
      sha256 "7721abc05806979b0e535335d0967b757ac0a65a114823350946584272ee1693"

      define_method(:install) do
        bin.install "sbctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/replicatedhq/sbctl/releases/download/v0.17.5/sbctl_darwin_arm64.tar.gz"
      sha256 "d3622d5e38590aa8b0a26c97666c0b71803a548694d872dc570148b494b70437"

      define_method(:install) do
        bin.install "sbctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/sbctl/releases/download/v0.17.5/sbctl_linux_amd64.tar.gz"
      sha256 "422ae06974905cbde6aa24d96884b97dc6c1ac54af8be06d373b2dc7658132d3"
      define_method(:install) do
        bin.install "sbctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/sbctl/releases/download/v0.17.5/sbctl_linux_arm64.tar.gz"
      sha256 "e88e9a4fb14cfe9cf9b721e45fe66dd5be508f4b74a2c9dc27aa485b509a50d6"
      define_method(:install) do
        bin.install "sbctl"
      end
    end
  end
end
