# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SupportBundle < Formula
  desc "Collect and redact support bundles for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/support-bundle-overview/"
  version "0.134.1"

  on_macos do
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.134.1/support-bundle_darwin_all.tar.gz"
    sha256 "6e77c3bbb99ac64290134fc06ddee7a1d333e8faf128f5613de0e25a3e5708da"

    def install
      bin.install "support-bundle"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.134.1/support-bundle_linux_amd64.tar.gz"
      sha256 "43da920966efc49743ba033e803cdd11e0b0ec36c19b7e4e5867e341b256eb3f"
      def install
        bin.install "support-bundle"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.134.1/support-bundle_linux_arm.tar.gz"
      sha256 "3d63b32fbf576c62c9e0f8585e8dc9ad28e4c4ac72b6638f0c8dac37c83678c1"
      def install
        bin.install "support-bundle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.134.1/support-bundle_linux_arm64.tar.gz"
      sha256 "b51fa1685c497b689e690df7a31c9fd4438b6e9466219face0c4c9b8432828f4"
      def install
        bin.install "support-bundle"
      end
    end
  end
end
