# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SupportBundle < Formula
  desc "Collect and redact support bundles for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/support-bundle-overview/"
  version "0.127.1"

  on_macos do
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.127.1/support-bundle_darwin_all.tar.gz"
    sha256 "add5266150b714eb30ed7a1ee6c11fd156179a8ea24e63c4c14c1f1cb36c3297"

    def install
      bin.install "support-bundle"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.127.1/support-bundle_linux_amd64.tar.gz"
      sha256 "40daa672e2d833b0bfcf9d23c8fa88c75846c8b39c166c47e755c378e0ce954a"
      def install
        bin.install "support-bundle"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.127.1/support-bundle_linux_arm.tar.gz"
      sha256 "dd40da00eb84310ff8af45be28edd1e5c6415f222051bb88d7842100755eb448"
      def install
        bin.install "support-bundle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.127.1/support-bundle_linux_arm64.tar.gz"
      sha256 "3ac32de57aa1b24fbd7331cd05863c37405b730ae012b9fb85b1865118803705"
      def install
        bin.install "support-bundle"
      end
    end
  end
end
