# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SupportBundle < Formula
  desc "Collect and redact support bundles for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/support-bundle-overview/"
  version "0.123.16"

  on_macos do
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.16/support-bundle_darwin_all.tar.gz"
    sha256 "b798e71fb995e16ce18945d13983bcc2a7b32701a60e1ef915c2ed6bf5b0f271"

    def install
      bin.install "support-bundle"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.16/support-bundle_linux_amd64.tar.gz"
      sha256 "6f2b11ad8c40de4de02f970d55636b681d1a6f8bbe03437347150f7ee3d2c6c6"
      def install
        bin.install "support-bundle"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.16/support-bundle_linux_arm.tar.gz"
      sha256 "dc4b236895abfab8303ac8405652adaff4192b199c24c386d84854b7a649721f"
      def install
        bin.install "support-bundle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.16/support-bundle_linux_arm64.tar.gz"
      sha256 "bbd20f535ff7d7330497e903f6f3016943bdb9bb23b65502876c2a0131cd52d6"
      def install
        bin.install "support-bundle"
      end
    end
  end
end
