# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preflight < Formula
  desc "A preflight checker and conformance test for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/preflight-overview/"
  version "0.123.0-alpha.5"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.0-alpha.5/preflight_linux_amd64.tar.gz"
    sha256 "c0768b57b375bda1404deb0b120e57f2bafb16f7bacf3c37e9e926c44b69f689"
    def install
      bin.install "preflight"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.0-alpha.5/preflight_linux_arm.tar.gz"
    sha256 "4d0efea7d212cde685cf5c53b2babe6f58978dece17fdda9eb6c9545dcc98ce4"
    def install
      bin.install "preflight"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.0-alpha.5/preflight_linux_arm64.tar.gz"
    sha256 "5c7fb1a13997c618bc42eb4760abbaa924e971bdeac36ab51f31d0e87a2849f5"
    def install
      bin.install "preflight"
    end
  end
end
