# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SupportBundle < Formula
  desc "Collect and redact support bundles for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/support-bundle-overview/"
  version "0.123.0-alpha.5"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.0-alpha.5/support-bundle_linux_amd64.tar.gz"
    sha256 "3918e9e07b4cf548dcd6385739d5c3da449a01da0e65c17384ca0eda4e9c3a0d"
    def install
      bin.install "support-bundle"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.0-alpha.5/support-bundle_linux_arm.tar.gz"
    sha256 "7bc459565a3ef12a45f6a55dae9d0c54f7fdc3ec4bb41a09f393c1849eeca996"
    def install
      bin.install "support-bundle"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/replicatedhq/troubleshoot/releases/download/v0.123.0-alpha.5/support-bundle_linux_arm64.tar.gz"
    sha256 "92f8db501487e8f0a40ba73ed3036b79e258940ffa86c33c9af2082a98aaf7c1"
    def install
      bin.install "support-bundle"
    end
  end
end
