# This file was generated by GoReleaser. DO NOT EDIT.
cask "preflight" do
  name "preflight"
  desc "A preflight checker and conformance test for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/preflight-overview/"
  version "0.123.0-alpha.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "preflight"

  on_linux do
    on_intel do
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v#{version}/preflight_linux_amd64.tar.gz"
      sha256 "6077b8a3dcc7efdbe2da2a802d334a2d85c3435de777791bdfe93db1d5a37498"
    end
    on_arm do
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v#{version}/preflight_linux_arm64.tar.gz"
      sha256 "11631a74ffa01b047940b70409b2bc6ab0487339a73a9557a5740b1693bb8597"
    end
  end

  # No zap stanza required
end
