# This file was generated by GoReleaser. DO NOT EDIT.
cask "support-bundle" do
  name "support-bundle"
  desc "Collect and redact support bundles for Kubernetes clusters."
  homepage "https://docs.replicated.com/reference/support-bundle-overview/"
  version "0.123.0-alpha.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "support-bundle"

  on_linux do
    on_intel do
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v#{version}/support-bundle_linux_amd64.tar.gz"
      sha256 "c4cb4d4dc2be36150ec0c582bb6c7a81eb6550b94e91b5ae73f991dae6f097d5"
    end
    on_arm do
      url "https://github.com/replicatedhq/troubleshoot/releases/download/v#{version}/support-bundle_linux_arm64.tar.gz"
      sha256 "e4c549b20b622e36ef7e3b9aebd34cb131626f57af2924395a0ca7d0c7266eeb"
    end
  end

  # No zap stanza required
end
